name       : lxappearance
version    : 0.6.3
release    : 2
source     :
    - https://sourceforge.net/projects/lxde/files/LXAppearance/lxappearance-0.6.3.tar.xz/download : 7222d858b8fef4b7967c42142d61e82ded6dd42dc5ef1d59caad775795928b38
license    : GPL-2.0-only
component  : desktop
summary    : LXAppearance is a theme switcher for LXDE and other Window managers.
description: |
    LXAppearance is the standard theme switcher of LXDE. Users are able to change the theme, icons, and fonts used by applications easily.
builddeps  :
    - pkgconfig(gtk+-3.0)
setup      : |
    %configure --enable-gtk3
build      : |
    %make
install    : |
    %make_install
